#!/bin/sh
set -eu

mysql --protocol=socket -uroot -p"${MYSQL_ROOT_PASSWORD}" <<SQL
CREATE DATABASE IF NOT EXISTS redblack_approval
  CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;
CREATE DATABASE IF NOT EXISTS redblack_office
  CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;
CREATE DATABASE IF NOT EXISTS redblack_audit
  CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;
CREATE USER IF NOT EXISTS '${APPROVAL_DB_USERNAME}'@'%'
  IDENTIFIED BY '${APPROVAL_DB_PASSWORD}';
ALTER USER '${APPROVAL_DB_USERNAME}'@'%'
  IDENTIFIED BY '${APPROVAL_DB_PASSWORD}';
GRANT ALL PRIVILEGES ON redblack_approval.* TO '${APPROVAL_DB_USERNAME}'@'%';
CREATE USER IF NOT EXISTS '${OFFICE_DB_USERNAME}'@'%' IDENTIFIED BY '${OFFICE_DB_PASSWORD}';
ALTER USER '${OFFICE_DB_USERNAME}'@'%' IDENTIFIED BY '${OFFICE_DB_PASSWORD}';
GRANT ALL PRIVILEGES ON redblack_office.* TO '${OFFICE_DB_USERNAME}'@'%';
CREATE USER IF NOT EXISTS '${AUDIT_DB_USERNAME}'@'%' IDENTIFIED BY '${AUDIT_DB_PASSWORD}';
ALTER USER '${AUDIT_DB_USERNAME}'@'%' IDENTIFIED BY '${AUDIT_DB_PASSWORD}';
GRANT ALL PRIVILEGES ON redblack_audit.* TO '${AUDIT_DB_USERNAME}'@'%';
FLUSH PRIVILEGES;
SQL
