#!/bin/sh
set -eu

mysql --protocol=socket -uroot -p"${MYSQL_ROOT_PASSWORD}" <<SQL
CREATE DATABASE IF NOT EXISTS redblack_approval
  CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;
CREATE USER IF NOT EXISTS '${APPROVAL_DB_USERNAME}'@'%'
  IDENTIFIED BY '${APPROVAL_DB_PASSWORD}';
ALTER USER '${APPROVAL_DB_USERNAME}'@'%'
  IDENTIFIED BY '${APPROVAL_DB_PASSWORD}';
GRANT ALL PRIVILEGES ON redblack_approval.* TO '${APPROVAL_DB_USERNAME}'@'%';
FLUSH PRIVILEGES;
SQL
